Attribute VB_Name = "GlobalModule"
' zmienne globalne nazw arkuszy dostepnych w danym projekcie
Global Const G_register_sh_nm = "register"
Global Const G_order_release_status_sh_nm = "ORDER RELEASE STATUS"
Global Const G_cont_pnoc_sh_nm = "Contracted . PNOC"
Global Const G_osea_sh_nm = "OSEA"
Global Const G_recent_build_plan_changes_sh_nm = "RECENT BUILD PLAN CHANGES"
Global Const G_main_sh_nm = "MAIN"
Global Const G_resp_sh_nm = "RESP"
Global Const G_open_issues_sh_nm = "OPEN ISSUES"
Global Const G_config_sh_nm = "config"
Global Const G_totals_sh_nm = "TOTALS"
Global Const G_del_conf_sh_nm = "DELIVERY CONFIRMATION"
Global Const G_one_pager_sh_nm = "ONE PAGER"
Global Const G_xq_sh_nm = "XQ HANDLER"
